"""finance.domain.models - the SQLAlchemy ORM. PRIVATE.

The declarative base, the shared column conventions, and the 15 tables of
`finance.*`. Every table here has a migration that creates it; the migration
file is the source of truth and this package mirrors it.

Conventions every table follows:

- **Amounts are `BigInteger` minor units**, never `Numeric`. `Numeric(18,2)` is
  wrong for JPY (0 decimals) and crypto, and accumulates FX rounding errors.
- **No `user_id`.** Single user, by decision (section E).
- **No `direction` column.** Sign plus `account_nature` is the encoding; adding
  a `direction` column contradicts it.
- **No cross-schema foreign keys.** One schema per module, enforced by grants.

THREE THINGS THAT ARE NOT OPTIONAL, and cost a whole schema if they are wrong.

1. `metadata` carries `schema="finance"`. Without it `ForeignKey("account.id")`
   raises `NoReferencedTableError` - and the fix people reach for next,
   qualifying the target as `"finance.account.id"`, is what trips
   `no_cross_schema_fk`, because that rule reads a schema-qualified reference
   target as a cross-schema reference. So the metadata carries the schema once,
   and every FK string in this package is UNQUALIFIED: SQLAlchemy renders it as
   a reference into `finance`, the checker reads an unqualified target as
   same-schema, and it is the same spelling the hand-written raw SQL in the
   migration uses. (This docstring deliberately does not spell the rendered
   clause out: it is prose, and the invariant checker scans raw text without
   knowing what is prose.)

2. **Every column type is explicit.** `Base.type_annotation_map` maps `int` to
   `BigInteger` because every surrogate key is BIGSERIAL, but the implicit
   annotations then lie about everything else:

   | annotation                     | would render                  | schema wants   |
   |--------------------------------|-------------------------------|----------------|
   | `sort_order: Mapped[int]`      | `BIGINT`                      | `INT`          |
   | `decimals: Mapped[int]`        | `BIGINT`                      | `SMALLINT`     |
   | `confidence: Mapped[Decimal]`  | `NUMERIC`                     | `NUMERIC(3,2)` |
   | `amount_base: Mapped[Decimal]` | `NUMERIC`                     | `NUMERIC(18,4)`|
   | `created_at: Mapped[datetime]` | `TIMESTAMP WITHOUT TIME ZONE` | `TIMESTAMPTZ`  |
   | `name: Mapped[str]`            | `VARCHAR`                     | `TEXT`         |

   None of those is caught by an import, and none of them fails until a value
   that fits the wide type does not fit the narrow one. Type every column.

3. No `Identity()`. `id: Mapped[int] = mapped_column(primary_key=True)` already
   renders `BIGSERIAL`, which is what the migration creates. `Identity()` would
   render `GENERATED BY DEFAULT AS IDENTITY` instead - a different DDL for no
   gain, and `mapped_column(BigInteger, identity=True)` raises `TypeError`.

What is deliberately NOT modelled: PostgreSQL sequences and triggers (DB-side),
and partial indexes. Every partial index - `idx_account_nature`,
`uq_sr_providertxn`, `idx_sr_open_pending`, `idx_jl_cat`, `idx_jl_uncat`,
`idx_jl_unmatched`, `idx_jl_transfer` - and the `NULLS NOT DISTINCT` unique
index `uq_recurring` are created by the migration, and each table says so at
the site.

`finance.domain.models` is PRIVATE: nothing outside the finance module may
import it, and `finance.public` is the only export surface.
"""

from __future__ import annotations

from datetime import datetime
from typing import Final

from sqlalchemy import BigInteger, DateTime, MetaData, func
from sqlalchemy.orm import DeclarativeBase, MappedColumn, mapped_column

__all__ = [
    "AMOUNT_TYPE",
    "NAMING_CONVENTION",
    "SCHEMA",
    "Base",
    "created_at_column",
    "metadata",
    "updated_at_column",
]

#: The one Postgres schema every table in this package lives in. Carried by the
#: metadata below; repeated here because every other layer needs it too, and
#: this is the module that owns the schema's name.
SCHEMA: Final[str] = "finance"

#: Every money column is a signed BIGINT of minor units. The exponent lives in
#: `currency.decimals`, which is the only authority for interpreting it.
AMOUNT_TYPE: Final = BigInteger

# Deterministic constraint names. Alembic autogenerate emits better diffs when
# constraint names are not random, and a name is required to drop or alter a
# constraint in a migration at all.
NAMING_CONVENTION: Final[dict[str, str]] = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


def created_at_column() -> MappedColumn[datetime]:
    """A `created_at` column: timezone-aware, server-defaulted, immutable.

    `MappedColumn[datetime]`, not `Mapped[datetime]`: what is returned here is a
    column object, which the declarative layer turns into a mapped attribute on
    the owning class. The type parameter is what mypy needs to accept the
    assignment `created_at: Mapped[datetime] = created_at_column()`.

    Server-defaulted on purpose. `created_at` is a fact about when the row
    arrived, and the database clock is the one clock that does not change
    timezone between the writer and the reader.
    """
    return mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )


def updated_at_column() -> MappedColumn[datetime]:
    """An `updated_at` column, the sibling of `created_at_column()`.

    The docstring on `created_at_column()` warns that a mutable timestamp
    column invites an UPDATE that sweeps in columns it should not touch. That
    warning is why exactly one table here has an `updated_at`:
    `journal_entry.updated_at`, maintained by the database through the
    `trg_journal_entry_updated_at` trigger in the migration.

    Deliberately no `onupdate=`. A Python-side default would be a second,
    competing source of the same fact, and it would only fire on statements
    that go through the ORM - a raw UPDATE in psql would leave the column
    stale. Server-side means every writer, including none at all, behaves the
    same. An `updated_at` with nothing to maintain it silently equals
    `created_at` forever; that is why the trigger is part of the same revision.
    """
    return mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )


class Base(DeclarativeBase):
    """Declarative base for every table in the finance schema."""

    metadata = MetaData(schema=SCHEMA, naming_convention=NAMING_CONVENTION)

    # Mapped[int] would make every primary key an INT4. Everything here is BIGINT
    # because the schema uses BIGSERIAL throughout. This is why every non-key
    # column states its own type; see the module docstring.
    type_annotation_map = {int: BigInteger}


#: Module-level alias, so `from finance.domain.models import metadata` reads the
#: same as `Base.metadata` without reaching through the class.
metadata: Final[MetaData] = Base.metadata


# The table modules, imported LAST and for their side effect: importing each one
# registers its classes on `Base.metadata`. Above this line `Base` exists but
# carries no tables, which is exactly why these imports cannot come earlier.
#
# `journal_line` and `transfer_match` reference each other's table by string
# ("journal_line.id" / "transfer_match.id") and neither module imports the
# other's class. SQLAlchemy resolves an FK string lazily, when DDL is emitted,
# by which time `__init__.py` has registered both - so the cycle costs nothing
# and neither module needs a `TYPE_CHECKING` import it does not otherwise use.
from finance.domain.models import (  # noqa: E402
    accounts,
    importer,
    ledger,
    recurring,
    reference,
    taxonomy,
    transfers,
)

__all__ += [
    "accounts",
    "importer",
    "ledger",
    "recurring",
    "reference",
    "taxonomy",
    "transfers",
]
